server:
  port: 8000
  servlet:
    context-path: /auth

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/auth"
    driverClassName: "com.postgresql.cj.jdbc.Driver"
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
